lyceum/about/urls.py
from django.urls import path

from about import views

app_name = "about"

urlpatterns = [
    path("", views.description, name="about"),
]

lyceum/homepage/urls.py
from django.urls import path

from homepage import views

app_name = "homepage"

urlpatterns = [
    path("", views.home, name="main"),
    path("echo/", views.echo, name="echo"),
    path("echo/submit/", views.echo_submit, name="echo_submit"),
    path("coffee/", views.coffee_view, name="coffee_view"),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("homepage.urls")),
    path("catalog/", include("catalog.urls")),
    path("about/", include("about.urls")),
    path("download/", include("download.urls")),
    path("feedback/", include("feedback.urls")),
    path("admin/", admin.site.urls),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

urlpatterns += i18n_patterns(
    path(
        "set_language/",
        include("django.conf.urls.i18n"),
        name="set_language",
    ),
)

lyceum/users/urls.py
from django.contrib.auth import views as views_django
from django.urls import path

from users import views


app_name = "users"

urlpatterns = [
    path(
        "login/",
        views_django.LoginView.as_view(
            template_name="users/login.html",
        ),
        name="login",
    ),
    path("logout/", views.logout_view, name="logout"),
    path(
        "signup/",
        views.signup_view,
        name="signup",
    ),
    path(
        "user_list/",
        views.user_list_view,
        name="user_list",
    ),
    path(
        "user_detail/<int:pk>",
        views.user_detail_view,
        name="user_detail",
    ),
    path(
        "profile/",
        views.profile_view,
        name="profile",
    ),
    path(
        "change-password/",
        views_django.PasswordChangeView.as_view(
            template_name="users/password_change.html",
            success_url="users:change-password-done",
        ),
        name="change-password",
    ),
    path(
        "change-password/done/",
        views_django.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="change-password-done",
    ),
    path(
        "reset-password/",
        views_django.PasswordResetView.as_view(
            template_name="users/password_reset.html",
            email_template_name="users/password_reset_email.html",
            subject_template_name="users/subjects/password_reset_subject.txt",
            success_url="users:password-reset-done",
        ),
        name="reset-password",
    ),
    path(
        "reset-password/done/",
        views_django.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password-reset-done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        views_django.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="users:password-reset-complete",
        ),
        name="password-reset-confirm",
    ),
    path(
        "reset-password/complete/",
        views_django.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password-reset-complete",
    ),
    path(
        "activate/<signed_username>/",
        views.activate_user_view,
        name="activate",
    ),
    path(
        "unlock-account/<signed_username>/",
        views.unlock_account,
        name="unlock-account",
    ),
]

lyceum/users/models.py
import re
import sys

from django.contrib.auth.models import (
    AbstractUser,
    BaseUserManager as DjangoUserManager,
)
from django.db import models


class CustomUserManager(DjangoUserManager):
    def normalize_email(self, email):
        email = super().normalize_email(email)
        email = email.lower()
        local_part, domain = email.split("@")

        local_part = local_part.split("+")[0]

        if domain in ["yandex.ru", "ya.ru"]:
            domain = "yandex.ru"
            local_part = local_part.replace(".", "-")
        elif domain == "gmail.com":
            local_part = local_part.replace(".", "")

        local_part = re.sub(r"\+.*", "", local_part)
        return f"{local_part}@{domain}"

    def get_queryset(self):
        return super().get_queryset().select_related("profile")

    def active(self):
        return self.filter(is_active=True).select_related("profile")

    def by_mail(self, email):
        normalized_email = self.normalize_email(email)
        return self.active().filter(email=normalized_email).first()


class CustomUser(AbstractUser):
    attempts_count = models.PositiveIntegerField(
        default=0,
    )

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.username


class User(CustomUser):
    objects = CustomUserManager()

    def save(self, *args, **kwargs):
        self.email = User.objects.normalize_email(self.email)
        super().save(*args, **kwargs)

    class Meta:
        proxy = True

    def get_profile(self):
        return self.profile


if "makemigrations" not in sys.argv and "migrate" not in sys.argv:
    User._meta.get_field("email")._unique = True


class Profile(models.Model):
    def get_upload_path(self, filename):
        return f"uploads/{self.id}/{filename}"

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        verbose_name="пользователь",
    )
    birthday = models.DateField(
        verbose_name="день рождения",
        null=True,
        blank=True,
    )
    image = models.ImageField(
        verbose_name="Фото профиля",
        upload_to=get_upload_path,
        null=True,
        blank=True,
    )
    coffee_count = models.PositiveIntegerField(
        default=0,
        verbose_name="количество переходов по /coffee/",
    )

    class Meta:
        verbose_name = "профиль"
        verbose_name_plural = "профили"

    def __str__(self):
        return f"{self.user.username} - Профиль"


__all__ = ()

lyceum/users/forms.py
from django import forms
from django.contrib import auth
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import ValidationError

from users.models import Profile, User


class SignUpForm(auth.forms.UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"

    def clean_email(self):
        email = self.cleaned_data.get("email")
        username = self.cleaned_data.get("username")
        if (
            email
            and User.objects.filter(email=email)
            .exclude(username=username)
            .exists()
        ):
            raise ValidationError("Email addresses must be unique.")

        return email

    class Meta(auth.forms.UserCreationForm.Meta):
        fields = [
            User.email.field.name,
            User.username.field.name,
            "password1",
            "password2",
        ]
        model = User


class ProfileUpdateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.birthday:
            self.initial["birthday"] = self.instance.birthday.strftime(
                "%Y-%m-%d",
            )

        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"

    class Meta:
        model = Profile
        fields = [
            Profile.birthday.field.name,
            Profile.image.field.name,
        ]
        widgets = {
            Profile.birthday.field.name: forms.DateInput(
                attrs={"class": "form-control", "type": "date"},
            ),
            Profile.coffee_count.field.name: forms.NumberInput(
                attrs={
                    "readonly": "readonly",
                    "disabled": "disabled",
                },
            ),
        }


class UserChangeForm(auth.forms.UserChangeForm):
    password = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"

    class Meta(auth.forms.UserChangeForm.Meta):
        fields = [
            User.first_name.field.name,
            User.last_name.field.name,
            User.email.field.name,
        ]
        exclude = [
            User.password.field.name,
        ]
        model = User


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(label="Имя пользователя или Email")

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        if "@" in username:
            user = User.objects.filter(email=username).first()
        else:
            user = User.objects.filter(username=username).first()

        if user and user.check_password(password):
            self.user_cache = user
        else:
            raise forms.ValidationError("Неправильные данные для входа.")

        return self.cleaned_data

    def get_user(self):
        return self.user_cache


__all__ = ()

lyceum/users/views.py
from django.conf import settings
from django.contrib import auth, messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.core import signing
from django.core.mail import send_mail
from django.http import HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse

from users.forms import (
    CustomAuthenticationForm,
    ProfileUpdateForm,
    SignUpForm,
    UserChangeForm,
)
from users.models import Profile, User


def signup_view(request):
    template_name = "users/signup.html"
    form = SignUpForm(request.POST or None)
    if form.is_valid() and request.method == "POST":
        user = form.save(commit=False)
        user.is_active = settings.DEFAULT_USER_IS_ACTIVE
        user.save()

        Profile.objects.create(
            user=user,
        )

        if not settings.DEFAULT_USER_IS_ACTIVE:
            signer = signing.TimestampSigner()
            signed_username = signer.sign(user.username)
            activate_link = request.build_absolute_uri(
                reverse(
                    "users:activate",
                    kwargs={"signed_username": signed_username},
                ),
            )

            send_mail(
                subject="Активация профиля",
                message=render_to_string(
                    "users/activation_email.txt",
                    {"activate_link": activate_link},
                ),
                from_email=settings.EMAIL_HOST,
                recipient_list=[form.cleaned_data["email"]],
            )
            messages.warning(
                request,
                "Вам необходимо активировать Ваш профиль. "
                "Проверьте указанную почту",
            )
        else:
            messages.success(
                request,
                "Вы зарегистрированы. Войдите с новыми данными",
            )

        return redirect("users:login")

    context = {"form": form}
    return render(request, template_name, context)


def activate_user_view(request, signed_username):
    template_name = "users/activation_success.html"
    user_model = auth.get_user_model()
    signer = signing.TimestampSigner()

    try:
        username = signer.unsign(signed_username, max_age=3600 * 12)
        user = user_model.objects.get(username=username)
    except (signing.BadSignature, user_model.DoesNotExist):
        return HttpResponseNotFound(
            "Неверная или просроченная ссылка активации",
        )

    user.is_active = True
    user.save()

    return render(request, template_name)


@login_required
def user_list_view(request):
    users_list = (
        Profile.objects.select_related("user")
        .filter(user__is_active=True)
        .only("user__username", "user__email", "id", "birthday", "image")
    )
    return render(request, "users/user_list.html", {"user_list": users_list})


def user_detail_view(request, pk):
    template_name = "users/user_detail.html"
    user = get_object_or_404(
        Profile.objects,
        user__is_active=True,
        pk=pk,
    )

    content = {
        "profile": user,
    }
    print()
    return render(request, template_name, content)


@login_required
def profile_view(request):
    template_name = "users/profile.html"
    user = request.user
    profile_form = ProfileUpdateForm(
        request.POST or None,
        request.FILES or None,
        instance=user.profile or None,
    )

    user_form = UserChangeForm(
        request.POST or None,
        instance=user,
    )
    context = {
        "user_form": user_form,
        "profile_form": profile_form,
    }
    if (
        profile_form.is_valid()
        and user_form.is_valid()
        and request.method == "POST"
    ):
        profile_form.save()
        user_form.save()
        request.session.modified = True
        messages.success(
            request,
            "Настройки сохранены.",
        )
        return redirect("users:profile")

    return render(request, template_name, context)


def login_view(request):
    template_name = "users/login.html"
    form = CustomAuthenticationForm(request, data=request.POST or None)

    if form.is_valid() and request.method == "POST":
        login(request, form.cleaned_data["user"])
        messages.success(request, "Вы успешно вошли в систему.")
        return redirect("users:profile")

    context = {"form": form}
    return render(request, template_name, context)


def logout_view(request):
    logout(request)
    messages.info(request, "Вы успешно вышли из системы.")
    return HttpResponseRedirect(reverse("users:login"))


def unlock_account(request, signed_username):
    template_name = "users/activation_success.html"
    user_model = User
    signer = signing.TimestampSigner()

    try:
        username = signer.unsign(signed_username, max_age=3600 * 7)
        user = user_model.objects.get(username=username)
    except (signing.BadSignature, user_model.DoesNotExist):
        return HttpResponseNotFound(
            "Неверная или просроченная ссылка активации",
        )

    user.is_active = True
    user.save()

    return render(request, template_name)


__all__ = ()

lyceum/templates/users/activation_success.html
{% extends "base.html" %}

{% block content %}

<h1>Аккаунт активирован!</h1>
<p>Ваш аккаунт был успешно активирован. Теперь вы можете войти, используя свои данные.</p>
<a href="{% url 'users:login' %}">Войти</a>

{% endblock %}

lyceum/templates/users/login.html
{% extends "base.html" %}

{% block content %}

<h1>Логин</h1>

{% include "users/login_form.html" %}

<p><a href="{% url 'users:reset-password' %}">Забыли пароль?</a></p>
<p><a href="{% url 'users:signup' %}">Нет аккаунта? Регистрация</a></p>

{% endblock %}

lyceum/templates/users/login_form.html
{% comment %} users/login_form.html {% endcomment %}
{% if form.errors %}
    <ul class="errorlist">
        {% for field in form %}
            {% for error in field.errors %}
                <li>{{ error|escape }}</li>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <li>{{ error|escape }}</li>
        {% endfor %}
    </ul>
{% endif %}

<form action="" method="post">
    {% csrf_token %}

    {% for field in form %}
        <div>
            <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                    <span>*</span>
                {% endif %}
            </label>
            {{ field }}

            {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help">
                    {{ field.help_text|safe }}
                </small>
            {% endif %}
        </div>
    {% endfor %}

    <button type="submit">Войти</button>
</form>

lyceum/templates/users/logout.html
{% extends "base.html" %}

{% block title %}Выход из аккаунта{% endblock title %}

{% block content %}

<h1>Вы вышли из своего аккаунта</h1>

{% endblock content %}

lyceum/templates/users/password_change.html
{% extends "base.html" %}

{% block title %}Смена пароля{% endblock title %}

{% block content %}

<h1>Смена пароля</h1>
<form method="POST" action='{% url "users:change-password" %}'>
    {% csrf_token %}
    {% for hidden_field in form.hidden_fields %}
      {{ hidden_field }}
    {% endfor %}
    {% if form.non_field_errors %}
      <div class="alert alert-danger" role="alert">
      {% for error in form.non_field_errors %}
        <div>{{ error }}</div>
      {% endfor %}
      </div>
    {% endif %}
    {% for field in form.visible_fields %}
      <div class="mb-3 {% if field.widget_type == 'checkbox' %}form-check{% endif %}">
        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
        {{ field }}
        {% if form.is_bound and field.errors %}
          {% for error in field.errors %}
            <div class="invalid-feedback d-block">
              {{ error }}
            </div>
          {% endfor %}
        {% endif %}
        {% if field.help_text %}
          <div class="form-text">{{ field.help_text }}</div>
        {% endif %}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Войти</button>
    <a href="{% url 'users:reset-password' %}" class="btn btn-link">Забыли пароль?</a>
</form>
{% endblock content %}

lyceum/templates/users/password_reset.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Сброс пароля{% endblock title %}

{% block content %}

<h1>Сбросить пароль</h1>
<form method="POST" action='{% url "users:reset-password" %}'>
  {% csrf_token %}
  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
  {% endfor %}
  {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      <div>{{ error }}</div>
    {% endfor %}
    </div>
  {% endif %}
  {% for field in form.visible_fields %}
    <div class="mb-3 {% if field.widget_type == 'checkbox' %}form-check{% endif %}">
      <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
      {{ field }}
      {% if form.is_bound and field.errors %}
        {% for error in field.errors %}
          <div class="invalid-feedback d-block">
            {{ error }}
          </div>
        {% endfor %}
      {% endif %}
      {% if field.help_text %}
        <div class="form-text">{{ field.help_text }}</div>
      {% endif %}
    </div>
  {% endfor %}
  <button type="submit" class="btn btn-primary">Далее</button>
</form>
{% endblock content %}

lyceum/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Сброс пароля{% endblock title %}

{% block content %}

<h1>Ваш пароль успешно сброшен.</h1>
<p>Используйте указанные вами данные при входе в аккаунт</p>

{% endblock content %}

lyceum/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Сброс пароля{% endblock title %}

{% block content %}

<h1>Процесс сброса пароля</h1>
{% if validlink %}
  <form method="POST">
      {% csrf_token %}
      {% for hidden_field in form.hidden_fields %}
      {{ hidden_field }}
      {% endfor %}
      {% if form.non_field_errors %}
      <div class="alert alert-danger" role="alert">
      {% for error in form.non_field_errors %}
          <div>{{ error }}</div>
      {% endfor %}
      </div>
      {% endif %}
      {% for field in form.visible_fields %}
      <div class="mb-3 {% if field.widget_type == 'checkbox' %}form-check{% endif %}">
          <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
          {{ field }}
          {% if form.is_bound and field.errors %}
          {% for error in field.errors %}
              <div class="invalid-feedback d-block">
              {{ error }}
              </div>
          {% endfor %}
          {% endif %}
          {% if field.help_text %}
          <div class="form-text">{{ field.help_text }}</div>
          {% endif %}
      </div>
      {% endfor %}
      <button type="submit" class="btn btn-primary">Сбросить пароль</button>
  </form>
{% else %}
  <p>
      Вероятно ссылка неверна или уже была использована
  </p>
{% endif %}
{% endblock content %}

lyceum/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Сброс пароля{% endblock title %}

{% block content %}

<h1>На указанную эл. почту был отправлен код для подтверждения сброса пароля</h1>
<p>Используйте указанную ссылку из эл. письма</p>

{% endblock content %}

lyceum/templates/users/password_reset_email.html
{% autoescape off %}
You're receiving this email because you requested a password reset for your user account at {{ site_name }}.

Please go to the following page and choose a new password:

{{ protocol }}://{{ domain }}{% url 'users:password-reset-confirm' uidb64=uid token=token %}

"Thanks for using our site!"
{% endautoescape %}

lyceum/templates/users/profile.html
{% extends "base.html" %}

{% block title %}Личный кабинет{% endblock title %}

{% block content %}

<h1>Личный кабинет</h1>
{% if messages %}
{% for message in messages %}
  <div class="alert alert-{{ message.tags }}" role="alert">
    {{ message }}
  </div>
{% endfor %}
{% endif %}
<form method="POST" enctype="multipart/form-data" class="mt-4">
  {% csrf_token %}
  {% for hidden_field in user_form.hidden_fields %}
      {{ hidden_field }}
  {% endfor %}
  {% if user_form.non_field_errors %}
      <div class="alert alert-danger" role="alert">
          {% for error in user_form.non_field_errors %}
              <div>{{ error }}</div>
          {% endfor %}
      </div>
  {% endif %}
  {% for field in user_form.visible_fields %}
      <div class="mb-3">
          <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
          {{ field }}
          {% if user_form.is_bound and field.errors %}
              {% for error in field.errors %}
                  <div class="invalid-feedback d-block">
                      {{ error }}
                  </div>
              {% endfor %}
          {% endif %}
          {% if field.help_text %}
              <div class="form-text">{{ field.help_text }}</div>
          {% endif %}
      </div>
  {% endfor %}
  {% for hidden_field in profile_form.hidden_fields %}
      {{ hidden_field }}
  {% endfor %}
  {% if profile_form.non_field_errors %}
      <div class="alert alert-danger" role="alert">
          {% for error in profile_form.non_field_errors %}
              <div>{{ error }}</div>
          {% endfor %}
      </div>
  {% endif %}
  {% for field in profile_form.visible_fields %}
      <div class="mb-3">
          <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
          {{ field }}
          {% if profile_form.is_bound and field.errors %}
              {% for error in field.errors %}
                  <div class="invalid-feedback d-block">
                      {{ error }}
                  </div>
              {% endfor %}
          {% endif %}
          {% if field.help_text %}
              <div class="form-text">{{ field.help_text }}</div>
          {% endif %}
      </div>
  {% endfor %}
  <button type="submit" class="btn btn-primary">Сохранить</button>
</form>
<form method="POST" action="{% url 'homepage:coffee_view' %}" class="mt-3">
  {% csrf_token %}
  <button type="submit" name="drink_coffee" class="btn btn-primary">Выпить кофе</button>
</form>
{% endblock content %}

lyceum/templates/users/signup.html
{% extends "base.html" %}

{% block content %}

<h1>Регистрация</h1>

<form method="POST">
{% csrf_token %}
{{ form.as_p }}

<button type="submit">Зарегистрироваться</button>
</form>

<p>После регистрации вам будет отправлено письмо с ссылкой для активации аккаунта.</p>

<p>Если у вас уже есть аккаунт, <a href="{% url 'users:login' %}">войдите здесь</a>.</p>

{% endblock %}

lyceum/templates/users/user_detail.html
{% extends "base.html" %}

{% block content %}

<h1>Профиль пользователя</h1>

<strong>Изображения</strong>
{% if profile.image %}
  <img src="/media/{{ profile.image }}" alt="profile Image">
{% else %}
  <span class="text-muted"><em>неуказано</em></span>
{% endif %}
<p><strong>Имя пользователя:</strong> {{ profile.user.username }}</p>
<p><strong>Email:</strong> {{ profile.user.email }}</p>

<p><strong>Имя:</strong> {% if profile.user.first_name %}{{ profile.user.first_name }}{% else %}не указано{% endif %}</p>
<p><strong>Фамилия:</strong> {% if profile.user.last_name %}{{ profile.user.last_name }}{% else %}не указано{% endif %}</p>
<p><strong>Дата рождения:</strong> {% if profile.birthday %}{{ profile.birthday|date:"d F" }}{% else %}не указано{% endif %}</p>

<p><strong>Количество попыток выпить кофе:</strong> {{ profile.coffee_count }}</p>

<a href="{% url 'users:profile' %}">Редактировать профиль</a>

{% endblock %}

lyceum/templates/users/user_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Список активных пользователей{% endblock title %}

{% block content %}

<div class="col-md-8 offset-md-2">
  <h2 class="text-center">Список активных пользователей</h2>
  <ul class="list-group">
  {% for profile in user_list %}
      <li class="list-group-item">
        {{ profile.user.username }}
        {{ profile.birthday|date:"d m" }}
        {% if profile.image %}
          <img src="/media/{{ profile.image }}" alt="User Image" width="50px" height="50px">
        {% endif %}
        <a href="{% url 'users:user_detail' pk=profile.id%}">Посмотреть</a>
      </li>
  {% empty %}
      <li class="list-group-item">Нет активных пользователей.</li>
  {% endfor %}
  </ul>
</div>

{% endblock content %}