lyceum/about/urls.py
from django.urls import path

from about import views

app_name = "about"

urlpatterns = [
    path("", views.description, name="about"),
]

lyceum/homepage/urls.py
from django.urls import path

from homepage import views

app_name = "homepage"

urlpatterns = [
    path("", views.home, name="main"),
    path("echo/", views.echo, name="echo"),
    path("echo/submit/", views.echo_submit, name="echo_submit"),
    path("coffee/", views.coffee_view, name="coffee_view"),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("homepage.urls")),
    path("catalog/", include("catalog.urls")),
    path("about/", include("about.urls")),
    path("download/", include("download.urls")),
    path("feedback/", include("feedback.urls")),
    path("admin/", admin.site.urls),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

urlpatterns += i18n_patterns(
    path(
        "set_language/",
        include("django.conf.urls.i18n"),
        name="set_language",
    ),
)

lyceum/users/urls.py
from django.contrib.auth import views as views_django
from django.urls import path

from users import views


app_name = "users"

urlpatterns = [
    path(
        "login/",
        views_django.LoginView.as_view(
            template_name="users/login.html",
        ),
        name="login",
    ),
    path("logout/", views.logout_view, name="logout"),
    path(
        "signup/",
        views.signup_view,
        name="signup",
    ),
    path(
        "user_list/",
        views.user_list_view,
        name="user_list",
    ),
    path(
        "user_detail/<int:pk>",
        views.user_detail_view,
        name="user_detail",
    ),
    path(
        "profile/",
        views.profile_view,
        name="profile",
    ),
    path(
        "change-password/",
        views_django.PasswordChangeView.as_view(
            template_name="users/password_change.html",
            success_url="users:change-password-done",
        ),
        name="change-password",
    ),
    path(
        "change-password/done/",
        views_django.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="change-password-done",
    ),
    path(
        "reset-password/",
        views_django.PasswordResetView.as_view(
            template_name="users/password_reset.html",
            email_template_name="users/password_reset_email.html",
            subject_template_name="users/subjects/password_reset_subject.txt",
            success_url="users:password-reset-done",
        ),
        name="reset-password",
    ),
    path(
        "reset-password/done/",
        views_django.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password-reset-done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        views_django.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="users:password-reset-complete",
        ),
        name="password-reset-confirm",
    ),
    path(
        "reset-password/complete/",
        views_django.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password-reset-complete",
    ),
    path(
        "activate/<signed_username>/",
        views.activate_user_view,
        name="activate",
    ),
    path(
        "unlock-account/<signed_username>/",
        views.unlock_account,
        name="unlock-account",
    ),
]

lyceum/templates/includes/footer.html
<footer class="footer mt-auto py-3 bg-light">
    <div class="container">
        <span class="text-muted" id="current-year" data-server-time="{% now 'Y-m-d H:i' %}">
            © {% now 'Y' %} Мой сайт. Все права защищены.
        </span>
    </div>
</footer>

lyceum/templates/includes/header.html
{% load static %}
{% load i18n %}
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'homepage:main' %}">
                <img src="{% static 'img/logo.png' %}" alt="Logo" width="30" height="30">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.view_name == 'homepage:main' %}active{% endif %}" href="{% url 'homepage:main' %}">{% trans "Главная" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.view_name == 'about:about' %}active{% endif %}" href="{% url 'about:about' %}">{% trans "О проекте" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.view_name == 'catalog:item_list' %}active{% endif %}" href="{% url 'catalog:item_list' %}">{% trans "Список товаров" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.view_name == 'feedback:feedback' %}active{% endif %}" href="{% url 'feedback:feedback' %}">{% trans "Обратная связь" %}</a>
                    </li>
                    <li class="nav-item">
                        {% if not user.is_authenticated %}
                            <a class="nav-link" href="{% url 'users:login' %}">Вход</a>
                        {% endif %}
                    </li>
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                            <a class="nav-link " href="{% url 'users:logout' %}">Выход</a>
                        {% endif %}
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " href="{% url 'users:profile' %}">Профиль</a>
                    </li>
                    {% if user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link " href="/admin/">Админ панель</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

lyceum/templates/includes/item_card.html
<div class="item-card">
    <h3>{{ item.name }}</h3>
    {{ item.text|truncatewords_html:10|safe }}

    <ul>
        {% for tag in item.tags.all %}
            <span class="tag">{{ tag.name }}</span>
        {% endfor %}
    </ul>
</div>