lyceum/about/urls.py
from django.urls import path

from about import views

app_name = "about"

urlpatterns = [
    path("", views.description, name="about"),
]

lyceum/catalog/urls.py
from django.urls import path, re_path, register_converter

from catalog import converters, views

register_converter(converters.PositiveIntegerConverter, "posint")

app_name = "catalog"

urlpatterns = [
    path("", views.item_list, name="item_list"),
    path("<int:pk>/", views.item_detail, name="item_detail"),
    path(
        "converter/<posint:number>/",
        views.number_view,
        name="converter_view",
    ),
    re_path(
        r"^re/(?P<number>0*[1-9]\d*)/$",
        views.number_view,
        name="number_view",
    ),
    path("new/", views.new_items, name="catalog_new"),
    path("friday/", views.friday_items, name="catalog_friday"),
    path("unverified/", views.unverified_items, name="catalog_unverified"),
]

lyceum/feedback/urls.py
from django.urls import path

from feedback import views

app_name = "feedback"

urlpatterns = [
    path("", views.feedback, name="feedback"),
]

lyceum/homepage/urls.py
from django.urls import path

from homepage import views

app_name = "homepage"

urlpatterns = [
    path("", views.home, name="main"),
    path("echo/", views.echo, name="echo"),
    path("echo/submit/", views.echo_submit, name="echo_submit"),
    path("coffee/", views.coffee_view, name="coffee_view"),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("homepage.urls")),
    path("catalog/", include("catalog.urls")),
    path("about/", include("about.urls")),
    path("download/", include("download.urls")),
    path("feedback/", include("feedback.urls")),
    path("admin/", admin.site.urls),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

urlpatterns += i18n_patterns(
    path(
        "set_language/",
        include("django.conf.urls.i18n"),
        name="set_language",
    ),
)

lyceum/homepage/forms.py
from django import forms


class EchoForm(forms.Form):
    text = forms.CharField(
        label="Текст",
        widget=forms.Textarea(),
        max_length=500,
        help_text="Максимум 500 символов",
    )


__all__ = ()

lyceum/homepage/views.py
from http import HTTPStatus

from django.http import HttpResponse
from django.shortcuts import render

from catalog.models import Item
from homepage.forms import EchoForm


def home(request):
    templates = "homepage/main.html"
    items = Item.objects.on_main()

    context = {
        "items": items,
    }
    return render(request, templates, context)


def echo(request):
    template = "homepage/echo.html"
    echo_form = EchoForm(request.POST or None)
    if request.method == "POST":
        return HttpResponse(
            "Страница не найдена",
            status=HTTPStatus.METHOD_NOT_ALLOWED,
        )

    context = {"echo_form": echo_form}

    return render(request, template, context)


def echo_submit(request):
    if request.method == "POST":
        echo_text = request.POST.get("text")
        return HttpResponse(
            echo_text,
            status=HTTPStatus.OK,
        )

    return HttpResponse(
        "Необходимо отправить текст для обратного вызова",
        status=HTTPStatus.METHOD_NOT_ALLOWED,
    )


def coffee_view(request):
    if request.user.is_authenticated:
        request.user.profile.coffee_count += 1
        request.user.profile.save()

    return HttpResponse("Я чайник", status=HTTPStatus.IM_A_TEAPOT)


__all__ = ()

lyceum/templates/homepage/echo.html
{% extends 'base.html' %}

{% block title %}Эхо{% endblock %}

{% block content %}

<form method="post" action="submit/">
    {% csrf_token %}
    <ul>
        {{ echo_form.as_p }}
    </ul>
    <input type="submit" value="Отправить">
</form>

{% endblock %}

lyceum/templates/homepage/main.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}Главная страница{% endblock %}

{% block content %}

<div class="jumbotron">
    <h1>{% trans "Добро пожаловать на наш сайт!" %}</h1>
    <p>{% trans "На главной странице можно найти краткую информацию о нашем проекте. " %}</p>
    <a class="btn btn-primary" href="{% url 'catalog:item_list' %}" role="button">Посмотреть товары<br></a>
    <a class="btn btn-primary" href="{% url 'feedback:feedback' %}">Обратная связь</a>
</div>
{% for item in items %}
    {% ifchanged item.category.name %}
        <h3>{{ item.category.name }}</h3>
    {% endifchanged %}
    {% include "includes/item_card.html" %}
{% endfor %}

{% endblock %}